ARG AIRFLOW_BASE_IMAGE=apache/airflow:3.0.6
FROM ${AIRFLOW_BASE_IMAGE}

RUN python -m pip install --no-cache-dir \
      apache-airflow==3.0.6 \
      apache-airflow-providers-fab==3.7.3 \
      boto3==1.40.20 \
      mlflow-skinny==3.3.2 \
      "psycopg[binary]==3.2.10" \
      qdrant-client==1.15.1
