apiVersion: v1
kind: Service
metadata:
  name: orion-release-risk-external
  namespace: orion-runtime
  labels:
    app.kubernetes.io/name: orion-release-risk
    app.kubernetes.io/part-of: keplerops-platform
spec:
  type: NodePort
  selector:
    app: isvc.orion-release-risk-predictor
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30083
