"""Validate ARWC staff publications, scheduling, consent and duty boundaries."""
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
import csv
import html
import io
import uuid
import zipfile
import yaml
from validate_office_life import Page, calendar


def require(ok, why):
    if not ok:
        raise ValueError('Community life: ' + why)


def moment(value):
    return datetime.fromisoformat(value)


def check_community_life(root, identity, roster, mail, docs, events, manifest=None):
    f = manifest if manifest is not None else yaml.safe_load(
        (root / 'authoring/community-life.yaml').read_text())
    people = {p['key']: p for p in roster}
    staff = {k for k, p in people.items() if p['employer'] == 'arwc'}
    all_mail = {m['id']: m for m in mail}
    messages = {k: m for k, m in all_mail.items() if k.startswith('cl-')}
    all_docs = {d['id']: d for d in docs}
    documents = {k: d for k, d in all_docs.items() if d['story'] == 'community-life'}
    calendars = {e['id']: e for e in events if e['id'].startswith('community-2026-')}
    histories = {h['id']: h for h in f['meetings']}
    snapshot = moment(identity['snapshot'])
    require(f['snapshot'] == identity['snapshot'] and f['required_base'] == '5d3545d'
            and f['accepted_workforce_commit'] == 'cf20e3e'
            and f['accepted_field_operations_commit'] == '700c43b', 'accepted base')
    require(set(calendars) == set(histories) and 600 <= len(calendars) <= 900, 'calendar inventory')
    require(100 <= len(f['publications']) <= 160, 'publication inventory')
    observed = {
        'publications': len(f['publications']),
        'comments': sum(len(p['comments']) for p in f['publications']),
        'reference_pages': len(f['references']), 'drafts': len(f['drafts']),
        'meetings': len(calendars),
        'meeting_states': dict(Counter(h['state'] for h in histories.values())),
        'categories': dict(Counter(h['category'] for h in histories.values())),
        'formal_notes': sum('minutes' in h for h in histories.values()),
        'people_actions': len(f['people_actions']), 'logical_messages': len(messages),
        'documents': len(documents),
        'retained_copies': sum(1 + len(m['to']) for m in messages.values()),
    }
    require(f['counts'] == observed, 'count reconciliation')

    def readers(d):
        return staff if d['audience'] == 'staff' else set(d.get('reader_keys', []))

    def restricted(d, expected):
        require(d['audience'] == 'restricted' and readers(d) == set(expected),
                'private readers: ' + d['id'])

    forbidden = ('scenario overlay', 'challenge flag', 'author-only', 'issue 131',
                 'generated by', 'codex', 'cinder typhoon', 'reader_keys', 'required_base')
    for d in documents.values():
        require(d['employer'] == 'arwc' and moment(d['published_at']) <= snapshot
                and readers(d) and readers(d) <= staff, 'document date or audience')
        require(d.get('text') and not any(s in d['text'].lower() for s in forbidden),
                'empty document or design leakage')
        if d['audience'] == 'staff':
            require(d.get('document_state') != 'draft', 'staff draft')
            require(not any(s in html.unescape(d['text']).lower() for s in (
                'company or ideas', 'ten minutes of complaining', 'retirement date',
                'my private appointment', 'learner question open')), 'private story on staff page')
    for m in messages.values():
        require({m['from'], *m['to']} <= staff and m['from'] not in m['to'], 'mail participants')
        require(moment(m['date']) < snapshot and m['body'].endswith('\n'), 'mail chronology')
        require(not any(s in m['body'].lower() for s in forbidden), 'mail design leakage')
        require(people[m['from']]['start_date'] <= m['date'][:10], 'mail before employment')
        if m.get('reply_to'):
            parent = all_mail[m['reply_to']]
            require(moment(parent['date']) < moment(m['date']), 'reply chronology')
        for key in m.get('attachments', []):
            d = documents[key]
            require(moment(d['published_at']) <= moment(m['date']), 'future attachment')
            require({m['from'], *m['to']} <= readers(d), 'attachment audience')

    for p in f['publications']:
        d = documents[p['id']]
        require(d['media_type'] == 'text/html' and d.get('document_state') == 'published',
                'publication format/state')
        require(readers(d) == set(p['reader_keys']) and p['author'] in readers(d), 'publication readers')
        require((p['scope'] == 'staff') == (d['audience'] == 'staff'), 'publication scope')
        if p['scope'] == 'team':
            require(readers(d) == {k for k in staff
                                  if people[k]['team'] == people[p['author']]['team']},
                    'team notice readership differs from roster')
        require(d['published_at'] == p['published_at'] and
                moment(p['posted_at']) <= moment(p['published_at']) <= snapshot, 'publication chronology')
        require(people[p['author']]['effective_date'] <= p['posted_at'][:10], 'historical author role')
        page = Page(d['text'])
        require(not page.comments and len(' '.join(page.words).split()) >= 45, 'empty or hidden publication')
        require(page.times == [p['posted_at']] + [c['date'] for c in p['comments']], 'publication timestamps')
        require(people[p['author']]['name'] in d['text'], 'publication author')
        for c in p['comments']:
            require(c['author'] in readers(d) and
                    moment(p['posted_at']) <= moment(c['date']) <= moment(p['published_at']),
                    'comment audience/chronology')
            require(html.escape(c['text']) in d['text'] and people[c['author']]['name'] in d['text'],
                    'missing comment')
        if p.get('after_event'):
            require(histories[p['after_event']]['state'] == 'completed' and
                    calendars[p['after_event']]['end'] <= p['posted_at'], 'premature recap')
    require(sum(not p['comments'] for p in f['publications']) >= len(f['publications']) // 2,
            'universal comments')
    require(not any('2026-07-20' <= p['posted_at'][:10] <= '2026-07-26'
                    for p in f['publications']), 'quiet week drift')
    for r in f['references']:
        d = documents[r['id']]
        require(d['audience'] == 'staff' and d['media_type'] == 'text/html'
                and d['published_at'] == r['published_at']
                and len(' '.join(Page(d['text']).words).split()) >= 100, 'reference substance')
    for draft in f['drafts']:
        d, publication = documents[draft['draft']], documents[draft['publication']]
        restricted(d, draft['permitted_readers'])
        a = messages[draft['approval']]
        require(d.get('document_state') == 'draft' and 'DRAFT' in d['text']
                and a['from'] == draft['author'] and draft['draft'] in a['attachments']
                and moment(d['published_at']) <= moment(a['date']) < moment(publication['published_at']),
                'draft approval')
    for consent in f['publication_consents']:
        approvals = [messages[k] for k in consent['approvals']]
        publication = next(p for p in f['publications'] if p['id'] == consent['publication'])
        require({a['from'] for a in approvals} == set(consent['people']) and
                all(moment(a['date']) < moment(publication['posted_at']) for a in approvals),
                'publication consent')
        require(html.escape(consent['approved_text']) in documents[consent['publication']]['text'],
                'approved wording changed')
        require(all(any(consent['approved_text'] in documents[k]['text'] for k in a['attachments'])
                    for a in approvals), 'consent does not identify exact text')
    withheld = f['withheld_draft']
    restricted(documents[withheld['document']], withheld['people'])
    require(documents[withheld['document']]['document_state'] == 'draft' and
            messages[withheld['withdrawal']]['from'] in withheld['people'], 'withheld contribution')

    # The accepted field books are independent scheduling evidence. Visiting crews
    # get travel/return allowance; timed observations are not free meeting slots.
    bookings = defaultdict(list)
    duties = defaultdict(list)

    def add(k, start, end, key):
        bookings[k].append((moment(start), moment(end), key))

    for e in events:
        if e['id'] in calendars or e['status'] == 'CANCELLED':
            continue
        for k in {e['organizer'], *e['attendees']}:
            if e.get('responses', {}).get(k) != 'DECLINED':
                add(k, e['start'], e['end'], e['id'])
        if e.get('location'):
            add('room:' + e['location'].split(' / ')[0], e['start'], e['end'], e['id'])
    for d in docs:
        if not d['id'].startswith('op-data-') or 'archive' not in d:
            continue
        key = d['id'].removeprefix('op-data-')
        if not key.startswith(('roster-', 'visits-', 'observations-')):
            continue
        with zipfile.ZipFile(root / d['archive']) as z:
            rows = list(csv.DictReader(io.StringIO(z.read(d['member']).decode())))
        for row in rows:
            if key.startswith('roster-'):
                duties[row['employee']].append(row)
            elif key.startswith('visits-'):
                for k in (row['lead'], row['partner']):
                    add(k, row['start'][:10] + 'T08:00:00-04:00',
                        row['start'][:10] + 'T12:45:00-04:00', row['visit_id'])
            else:
                t = moment(row['observed_at'])
                add(row['recorded_by'], (t - timedelta(minutes=10)).isoformat(),
                    (t + timedelta(minutes=15)).isoformat(), row['observation_id'])

    def check_ics(d, e, method, when, respondent=None):
        c = calendar(d['text'])
        utc = lambda s: moment(s).astimezone(timezone.utc).strftime('%Y%m%dT%H%M%SZ')
        uid = str(uuid.uuid5(uuid.NAMESPACE_URL, 'urn:cinder-workplace:' + e['id'])) + '@alterrawaterco.com'
        require(c['UID'] == [uid] and c['METHOD'] == [method], 'calendar UID/method')
        require(c['DTSTART'] == [utc(e['start'])] and c['DTEND'] == [utc(e['end'])]
                and c['DTSTAMP'] == [utc(when)], 'calendar times')
        require(c['SEQUENCE'] == ['1' if method == 'CANCEL' else '0'], 'calendar sequence')
        expected_status = 'CANCELLED' if method == 'CANCEL' else (
            'TENTATIVE' if e['status'] == 'TENTATIVE' else 'CONFIRMED')
        require(c['STATUS'] == [expected_status] and
                c['ORGANIZER'] == ['mailto:' + people[e['organizer']]['email']], 'calendar status/organizer')
        expected = defaultdict(list)
        for k in ([respondent] if respondent else e['attendees']):
            field = 'ATTENDEE' if method == 'CANCEL' else 'ATTENDEE;PARTSTAT=' + (
                e['responses'][k] if respondent else 'NEEDS-ACTION') + (';RSVP=TRUE' if method == 'REQUEST' else '')
            expected[field].append('mailto:' + people[k]['email'])
        require({k: v for k, v in c.items() if k.startswith('ATTENDEE')} == dict(expected),
                'calendar response people')
        escape = lambda s: s.replace('\\', '\\\\').replace('\n', '\\n').replace(';', '\\;').replace(',', '\\,')
        require(c['SUMMARY'] == [escape(e['summary'])] and c['LOCATION'] == [escape(e['location'])]
                and c['DESCRIPTION'] == [escape(e['description'])], 'calendar text')

    def is_operations(k):
        return people[k]['department'] == 'Operations, treatment, and distribution'

    for key, e in calendars.items():
        h = histories[key]
        audience = {e['organizer'], *e['attendees']}
        start, end, created = map(moment, (e['start'], e['end'], e['created_at']))
        require(audience == set(h['invitees']) and audience <= staff, 'meeting audience')
        require(created < start < end and created < snapshot
                and created <= moment(e['updated_at']) <= snapshot, 'meeting chronology')
        require(set(e['responses']) == set(e['attendees']) and set(e['responses'].values()) <=
                {'ACCEPTED', 'DECLINED', 'TENTATIVE', 'NEEDS-ACTION'}, 'response inventory')
        require(all(people[k]['effective_date'] <= e['start'][:10] for k in audience), 'historical meeting role')
        room = f['rooms'][e['room']]
        require(e['location'] == room['name'] and set(e['in_person']) <= audience
                and len(e['in_person']) <= room['capacity'], 'room capacity/location')
        require(e['room'] != 'remote' or not e['in_person'], 'remote physical seats')
        require(all(e['responses'].get(k) != 'DECLINED' for k in e['in_person']), 'declined physical attendee')
        invitation = messages[h['invitation']]
        require(invitation['from'] == e['organizer'] and set(invitation['to']) == set(e['attendees'])
                and invitation['date'] == e['created_at'], 'invitation routing')
        request = documents[invitation['attachments'][0]]
        restricted(request, audience)
        check_ics(request, e, 'REQUEST', invitation['date'])
        require(set(h['responses']) == {k for k, v in e['responses'].items() if v != 'NEEDS-ACTION'},
                'response lacks evidence')
        for k, response in h['responses'].items():
            m, d = messages[response['message']], documents[response['document']]
            require(m['from'] == k and m['to'] == [e['organizer']] and
                    response['status'] == e['responses'][k] and
                    created < moment(m['date']) < start and d['id'] in m['attachments']
                    and m['reply_to'] == h['invitation'], 'response evidence')
            restricted(d, [k, e['organizer']])
            check_ics(d, e, 'REPLY', m['date'], k)
        if h['state'] == 'completed':
            require(e['status'] == 'CONFIRMED' and end < snapshot and h['actual_attendees'], 'false completion')
            actual = set(h['actual_attendees'])
            require(actual <= audience and e['organizer'] in actual and
                    all(e['responses'].get(k) not in ('DECLINED', 'TENTATIVE') for k in actual), 'false attendance')
            completion = messages[h['completion']]
            require(moment(completion['date']) >= end and completion['from'] == e['organizer']
                    and completion['reply_to'] == h['invitation'], 'completion evidence')
            require(completion['body'].split('\n', 1)[0] ==
                    'Present: ' + ', '.join(people[k]['name'] for k in h['actual_attendees']) + '.',
                    'attendance differs from completed record')
            if h.get('minutes'):
                note = documents[h['minutes']]
                restricted(note, actual)
                require(moment(note['published_at']) >= end and h['minutes'] in completion['attachments'],
                        'minutes chronology')
                if h['category'] == 'check-in':
                    require(note.get('collection') == 'employment', 'private check-in collection')
        elif h['state'] == 'cancelled':
            require(e['status'] == 'CANCELLED' and e['sequence'] == 1 and not h['actual_attendees']
                    and not h.get('minutes') and not h.get('completion'), 'cancelled attendance')
            m = messages[h['cancellation']]
            require(created < moment(m['date']) < start and m['date'] == e['updated_at'], 'cancellation chronology')
            d = documents[m['attachments'][0]]
            restricted(d, audience)
            check_ics(d, e, 'CANCEL', m['date'])
        else:
            require(h['state'] == 'planned' and start > snapshot and e['status'] == 'TENTATIVE'
                    and not h['actual_attendees'] and not h.get('minutes') and not h.get('completion'),
                    'future meeting completed')
        if h['category'] == 'check-in':
            require(h['manager'] == people[h['employee']]['manager'] == e['organizer']
                    and e['attendees'] == [h['employee']], 'check-in reporting line')
            if h.get('follows'):
                previous = histories[h['follows']]
                require(previous['state'] == 'completed' and previous['employee'] == h['employee']
                        and calendars[previous['id']]['end'] < e['start'], 'follow-up chronology')
        if h.get('working_example'):
            d = documents[h['working_example']]
            require(audience <= readers(d) and moment(d['published_at']) < start
                    and 'Original wording:' in d['text'] and 'Working wording:' in d['text'],
                    'missing practical example')
        if h.get('learning_scope'):
            require('no operating qualification' in h['learning_scope'], 'learning authority')
        cover = set(e['cover'])
        agreements = h.get('cover_agreements', [])
        require(cover == {a['person'] for a in agreements} and not cover & audience, 'cover identity')
        required_teams = {people[k]['team'] for k in audience if is_operations(k)
                          or people[k]['team'] in ('Customer contact', 'Service desk')}
        if h['state'] != 'planned':
            require(required_teams == {a['team'] for a in agreements}, 'missing duty cover')
        for a in agreements:
            k = a['person']; m = messages[a['message']]
            require(people[k]['team'] == a['team'] and k not in {'owen', 'awm029', 'awm046', 'awm080'}
                    and people[k]['effective_date'] <= e['start'][:10], 'ineligible cover')
            require(set(a['released']) == {k for k in audience if people[k]['team'] == a['team']},
                    'cover release people')
            require(m['from'] == k and m['to'] == [e['organizer']] and not m.get('attachments')
                    and moment(m['date']) < start and e['summary'] not in m['subject'], 'cover privacy/chronology')
        if h['state'] == 'cancelled':
            require(len(h.get('cover_withdrawals', [])) == len(cover), 'cover not withdrawn')
            for mid in h.get('cover_withdrawals', []):
                m = messages[mid]
                require(set(m['to']) <= cover and not m.get('attachments')
                        and moment(m['date']) < start, 'cover cancellation privacy')
            continue
        booked = {k for k in audience if e['responses'].get(k) != 'DECLINED'} | cover
        for k in booked:
            if is_operations(k) and '2026-08-03' <= e['start'][:10] < '2026-09-14':
                require(any(moment(d['start']) <= start and end <= moment(d['end']) for d in duties[k]),
                        'off-shift booking: ' + key + '/' + k)
        resources = set(booked)
        if e['room'] != 'remote':
            resources.add('room:' + e['location'])
        for r in e.get('resources', []):
            require(r in f['resources'], 'unknown resource')
            resources.add('resource:' + r)
        for resource in resources:
            for a, b, other in bookings[resource]:
                require(not (start < b and a < end), 'booking conflict for ' + resource + ': ' + key + '/' + other)
            add(resource, e['start'], e['end'], key)

    for action in f['people_actions']:
        k, manager, officer = action['employee'], action['manager'], action['officer']
        require(people[k]['manager'] == manager and officer in ('awm221', 'awm222'), 'personnel authority')
        d = documents[action['document']]
        restricted(d, [k, manager, officer])
        require(d.get('collection') == 'employment' and histories[action['meeting']]['employee'] == k
                and calendars[action['meeting']]['end'] < d['published_at'], 'personnel history')
        require(all(set(messages[mid]['to']) | {messages[mid]['from']} == {k, manager, officer}
                    for mid in action['messages']), 'personnel correspondence readers')

    rows = list(csv.DictReader(io.StringIO(documents[f['availability_document']]['text'])))
    expected_rows = []
    shared_rooms = {r['name'] for key, r in f['rooms'].items() if key != 'remote'}
    for e in events:
        if e['status'] == 'CANCELLED' or e.get('employer') != 'arwc':
            continue
        names = ([e['location']] if e.get('location') in shared_rooms else []) + [
            f['resources'][r]['name'] for r in e.get('resources', []) if r in f['resources']]
        expected_rows.extend({'resource': n, 'start': e['start'], 'end': e['end'], 'status': 'Reserved'} for n in names)
    require(rows == sorted(expected_rows, key=lambda r: (r['resource'], r['start'], r['end'], r['status'])),
            'shared availability privacy/inventory')
    require(documents[f['availability_document']]['audience'] == 'staff', 'availability audience')
    require(f['outreach_date'] is None and f['staff_walk_date'] is None, 'unsettled date made definite')
    for link in f['story_links']:
        m = messages[link['message']]
        require({m['from'], *m['to']} == set(link['circle']) and m.get('reply_to') == link['parent'],
                'private story audience/thread')
    require(set(f['accepted_story_records']) <= set(all_mail), 'accepted story evidence missing')
    lunch = next(e for e in events if e['id'] == f['existing_lunch'])
    require(lunch['start'] == '2026-09-22T12:30:00-04:00'
            and not any({'rosa', 'nadia'} <= {e['organizer'], *e['attendees']}
                        and e['start'][:10] == '2026-09-22' for e in calendars.values()), 'duplicate future lunch')
    photo = next(d for d in documents.values() if d['title'] == 'Ordinary light: results and next steps')
    require(photo['published_at'] > all_mail['a-photo-4']['date'] and
            all(s in html.unescape(photo['text']) for s in ('Kaisa Kelswick', 'Theo Marrivel', 'Mina Selverin', 'Owen Vardell')),
            'photography chronology/people')
    # Approved outreach prose is a real retained handout, not an empty promise.
    handout = documents['community-outreach-handout']
    restricted(handout, ['owen', 'mina', 'rosa'])
    require(handout['published_at'] > all_mail['a-outreach-3']['date'] and
            'What happens before water reaches our tap?' in handout['text']
            and 'work continues throughout the day' in handout['text'], 'outreach handout continuity')
    return observed
