from __future__ import annotations

from keplerops_runtime.foundation.auth_storage import _postgres


def _ensure_model_supply_schema() -> None:
    """Apply additive Module 02 supply schemas to retained rehearsal databases."""

    with _postgres() as connection:
        connection.execute(
            "CREATE TABLE IF NOT EXISTS data_dependencies ("
            "dependency_id text PRIMARY KEY CHECK (dependency_id ~ '^ddp-[0-9a-f]{24}$'), "
            "range_instance text NOT NULL, participant text NOT NULL, reset_generation integer "
            "NOT NULL, challenge_id text NOT NULL CHECK (challenge_id='kep-m02-i'), "
            "dependency_name text NOT NULL CHECK (dependency_name='keplerops-eval-set'), "
            "dependency_version text NOT NULL CHECK (dependency_version='2.0.0-poisoned'), "
            "manifest jsonb NOT NULL, manifest_digest text NOT NULL CHECK (manifest_digest ~ "
            "'^sha256:[0-9a-f]{64}$'), signature text NOT NULL CHECK (signature ~ "
            "'^sha256:[0-9a-f]{64}$'), publisher text NOT NULL CHECK (publisher='gateway-api'), "
            "created_at timestamptz NOT NULL DEFAULT clock_timestamp(), UNIQUE (range_instance, "
            "participant, reset_generation, manifest_digest))"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS data_dependency_jobs ("
            "job_id text PRIMARY KEY CHECK (job_id ~ '^ddj-[0-9a-f]{24}$'), dependency_id text "
            "NOT NULL REFERENCES data_dependencies(dependency_id) ON DELETE CASCADE, range_instance "
            "text NOT NULL, participant text NOT NULL, reset_generation integer NOT NULL, "
            "challenge_id text NOT NULL CHECK (challenge_id='kep-m02-i'), status text NOT NULL "
            "CHECK (status IN ('queued','running','succeeded','failed')), workflow_id text, "
            "consumed_digest text CHECK (consumed_digest IS NULL OR consumed_digest ~ "
            "'^sha256:[0-9a-f]{64}$'), baseline_accuracy double precision, resolved_accuracy "
            "double precision, regression double precision, failure_class text, created_at "
            "timestamptz NOT NULL DEFAULT clock_timestamp(), started_at timestamptz, completed_at "
            "timestamptz, UNIQUE (range_instance, participant, reset_generation, dependency_id))"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS model_dependencies ("
            "dependency_id text PRIMARY KEY CHECK (dependency_id ~ '^mdp-[0-9a-f]{24}$'), "
            "range_instance text NOT NULL, participant text NOT NULL, reset_generation integer "
            "NOT NULL, challenge_id text NOT NULL CHECK (challenge_id='kep-m02-j'), dependency_name "
            "text NOT NULL CHECK (dependency_name='keplerops-policy-model'), source_url text NOT "
            "NULL, source_digest text NOT NULL CHECK (source_digest ~ '^sha256:[0-9a-f]{64}$'), "
            "registry_run_id text NOT NULL, registry_model_name text NOT NULL, "
            "registry_model_version text NOT NULL, resolved_digest text NOT NULL CHECK "
            "(resolved_digest ~ '^sha256:[0-9a-f]{64}$'), clean_decision text NOT NULL CHECK "
            "(clean_decision IN ('allow','deny')), resolved_decision text NOT NULL CHECK "
            "(resolved_decision IN ('allow','deny')), registry_alias text NOT NULL CHECK "
            "(registry_alias='consumer'), created_at timestamptz NOT NULL DEFAULT clock_timestamp(), "
            "UNIQUE (range_instance, participant, reset_generation, source_digest))"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS web_deliveries ("
            "delivery_id text PRIMARY KEY CHECK (delivery_id ~ '^wex-[0-9a-f]{24}$'), "
            "range_instance text NOT NULL, participant text NOT NULL, reset_generation integer "
            "NOT NULL, challenge_id text NOT NULL CHECK (challenge_id='kep-m02-k'), nonce text NOT "
            "NULL CHECK (nonce ~ '^[0-9a-f]{24}$'), content text NOT NULL, expected_digest text NOT "
            "NULL CHECK (expected_digest ~ '^sha256:[0-9a-f]{64}$'), stored_digest text CHECK "
            "(stored_digest IS NULL OR stored_digest ~ '^sha256:[0-9a-f]{64}$'), stored_path text, "
            "writer text CHECK (writer IS NULL OR writer='participant-public-exploit'), "
            "browser_digest text CHECK (browser_digest IS NULL OR browser_digest ~ "
            "'^sha256:[0-9a-f]{64}$'), browser_process_id integer CHECK (browser_process_id IS NULL "
            "OR browser_process_id > 0), effect_digest text CHECK (effect_digest IS NULL OR "
            "effect_digest ~ '^sha256:[0-9a-f]{64}$'), created_at timestamptz NOT NULL DEFAULT "
            "clock_timestamp(), written_at timestamptz, visited_at timestamptz, UNIQUE "
            "(range_instance, participant, reset_generation, nonce))"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS supply_attempts ("
            "id bigserial PRIMARY KEY, range_instance text NOT NULL, participant text NOT NULL, "
            "reset_generation integer NOT NULL, challenge_id text NOT NULL CHECK (challenge_id IN "
            "('kep-m02-i','kep-m02-j','kep-m02-k')), object_id text NOT NULL, status text NOT NULL "
            "CHECK (status IN ('passed','not_satisfied')), failure_class text NOT NULL, created_at "
            "timestamptz NOT NULL DEFAULT clock_timestamp())"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS runtime_dependencies ("
            "dependency_id text PRIMARY KEY CHECK (dependency_id ~ '^rtp-[0-9a-f]{24}$'), "
            "range_instance text NOT NULL, participant text NOT NULL, reset_generation integer "
            "NOT NULL, challenge_id text NOT NULL CHECK (challenge_id='kep-m02-h'), genuine_name "
            "text NOT NULL CHECK (genuine_name='keplerops-eval-runtime'), published_name text NOT "
            "NULL CHECK (published_name='keplerops-eval-runtlme'), package_version text NOT NULL "
            "CHECK (package_version='1.0.0'), resolver text NOT NULL CHECK "
            "(resolver='pip-gitea-pypi'), genuine_digest text NOT NULL CHECK (genuine_digest ~ "
            "'^sha256:[0-9a-f]{64}$'), resolved_digest text NOT NULL CHECK (resolved_digest ~ "
            "'^sha256:[0-9a-f]{64}$'), installed_digest text NOT NULL CHECK (installed_digest ~ "
            "'^sha256:[0-9a-f]{64}$'), genuine_decision text NOT NULL CHECK "
            "(genuine_decision IN ('allow','deny')), selected_decision text NOT NULL CHECK "
            "(selected_decision IN ('allow','deny')), deceptive_identity boolean NOT NULL, "
            "resolver_process_id integer NOT NULL CHECK (resolver_process_id > 0), "
            "genuine_process_id integer NOT NULL CHECK (genuine_process_id > 0), "
            "worker_process_id integer NOT NULL CHECK (worker_process_id > 0), "
            "worker_effect_digest text NOT NULL CHECK (worker_effect_digest ~ "
            "'^sha256:[0-9a-f]{64}$'), created_at timestamptz NOT NULL DEFAULT clock_timestamp())"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS sandbox_evaluations ("
            "evaluation_id text PRIMARY KEY CHECK (evaluation_id ~ '^sbe-[0-9a-f]{24}$'), "
            "dependency_id text NOT NULL REFERENCES runtime_dependencies(dependency_id) ON DELETE "
            "CASCADE, range_instance text NOT NULL, participant text NOT NULL, reset_generation "
            "integer NOT NULL, challenge_id text NOT NULL CHECK (challenge_id='kep-m02-m'), "
            "artifact_digest text NOT NULL CHECK (artifact_digest ~ '^sha256:[0-9a-f]{64}$'), "
            "sandbox_digest text NOT NULL CHECK (sandbox_digest ~ '^sha256:[0-9a-f]{64}$'), "
            "worker_digest text NOT NULL CHECK (worker_digest ~ '^sha256:[0-9a-f]{64}$'), "
            "sandbox_profile text NOT NULL CHECK (sandbox_profile='analysis'), worker_profile text "
            "NOT NULL CHECK (worker_profile='worker'), sandbox_decision text NOT NULL CHECK "
            "(sandbox_decision IN ('allow','deny')), worker_decision text NOT NULL CHECK "
            "(worker_decision IN ('allow','deny')), sandbox_effect boolean NOT NULL, worker_effect "
            "boolean NOT NULL, environment_sensitive boolean NOT NULL, worker_effect_digest text "
            "NOT NULL CHECK (worker_effect_digest ~ '^sha256:[0-9a-f]{64}$'), "
            "resolver_process_id integer NOT NULL CHECK (resolver_process_id > 0), sandbox_process_id "
            "integer NOT NULL CHECK (sandbox_process_id > 0), worker_process_id integer NOT NULL "
            "CHECK (worker_process_id > 0), created_at timestamptz NOT NULL DEFAULT "
            "clock_timestamp())"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS runtime_supply_attempts ("
            "id bigserial PRIMARY KEY, range_instance text NOT NULL, participant text NOT NULL, "
            "reset_generation integer NOT NULL, challenge_id text NOT NULL CHECK (challenge_id IN "
            "('kep-m02-h','kep-m02-m')), object_id text NOT NULL, status text NOT NULL CHECK "
            "(status IN ('passed','not_satisfied')), failure_class text NOT NULL, created_at "
            "timestamptz NOT NULL DEFAULT clock_timestamp())"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS spearphish_campaigns ("
            "campaign_id text PRIMARY KEY CHECK (campaign_id ~ '^sph-[0-9a-f]{24}$'), "
            "range_instance text NOT NULL, participant text NOT NULL, reset_generation integer "
            "NOT NULL, challenge_id text NOT NULL CHECK (challenge_id='kep-m02-l'), "
            "text_generation_id text NOT NULL CHECK (text_generation_id ~ '^txt-[0-9a-f]{24}$'), "
            "text_model text NOT NULL, text_digest text NOT NULL CHECK (text_digest ~ "
            "'^sha256:[0-9a-f]{64}$'), image_job_id text NOT NULL, image_model text NOT NULL, "
            "image_revision text NOT NULL CHECK (image_revision ~ '^[0-9a-f]{40}$'), "
            "image_digest text NOT NULL CHECK (image_digest ~ '^sha256:[0-9a-f]{64}$'), "
            "smtp_message_id text NOT NULL, smtp_sender text NOT NULL, smtp_recipient text NOT "
            "NULL, imap_observed boolean NOT NULL, attachment_digest text NOT NULL CHECK "
            "(attachment_digest ~ '^sha256:[0-9a-f]{64}$'), recipient_model text NOT NULL, "
            "recipient_decision text NOT NULL CHECK (recipient_decision IN ('disclose','deny')), "
            "identity_provider text, token_subject text, token_scope text, token_digest text CHECK "
            "(token_digest IS NULL OR token_digest ~ '^sha256:[0-9a-f]{64}$'), token_issued_at "
            "bigint, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), UNIQUE "
            "(range_instance, participant, reset_generation, smtp_message_id))"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS spearphish_attempts ("
            "id bigserial PRIMARY KEY, range_instance text NOT NULL, participant text NOT NULL, "
            "reset_generation integer NOT NULL, challenge_id text NOT NULL CHECK "
            "(challenge_id='kep-m02-l'), object_id text NOT NULL, status text NOT NULL CHECK "
            "(status IN ('passed','not_satisfied')), failure_class text NOT NULL, created_at "
            "timestamptz NOT NULL DEFAULT clock_timestamp())"
        )
