log:
  level: info
  job_level: info

runner:
  file: /runner/.runner
  capacity: 1
  timeout: 20m
  shutdown_timeout: 2m
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  report_interval: 1s
  labels:
    - m05-orion-release-linux:host

cache:
  enabled: false

container:
  docker_host: "-"
  force_pull: false
  force_rebuild: false

host:
  workdir_parent: /runner/workspace
