ARG BASE_IMAGE=coredns/coredns:1.14.6@sha256:900f9c109f7a33545d3c811516e8376df9019147b750f5ce3e254468769176ea
FROM ${BASE_IMAGE}

COPY assets/services/platform-network/coredns/Corefile /etc/coredns/Corefile

EXPOSE 53/tcp 53/udp 8080/tcp 8181/tcp 9153/tcp
ENTRYPOINT ["/coredns"]
CMD ["-conf", "/etc/coredns/Corefile"]
